export const EventHistoryData = [
  {
    name: "Cloud Innovation Summit",
    date: "2024-10-15",
    speaker: "Jane Doe",
    completed: true,
  },
  {
    name: "Blockchain Revolution Conference",
    date: "2024-11-05",
    speaker: "Dr. Peter Smith",
    completed: false,
  },
  {
    name: "AI in Healthcare Symposium",
    date: "2024-12-01",
    speaker: "Dr. Aisha Malik",
    completed: true,
  },
  {
    name: "Future of Fintech Forum",
    date: "2024-10-25",
    speaker: "Jane Doe",
    completed: true,
  },
  {
    name: "Data Analytics in Business",
    date: "2024-11-12",
    speaker: "Rachel Moore",
    completed: true,
  },
  {
    name: "Sustainable Energy Expo",
    date: "2024-09-28",
    speaker: "Prof. Alan Green",
    completed: true,
  },
  {
    name: "Web3 Interfaces Workshop",
    date: "2024-10-10",
    speaker: "Kevin Adams",
    completed: false,
  },
  {
    name: "Cybersecurity for Startups",
    date: "2024-11-19",
    speaker: "Emily Zhang",
    completed: true,
  },
  {
    name: "Smart Cities Forum",
    date: "2024-10-18",
    speaker: "Dr. Maria Hernandez",
    completed: false,
  },
  {
    name: "Tech Safari Mixer",
    date: "2024-09-30",
    speaker: "Guest Panel",
    completed: false,
  },
  {
    name: "Quantum Computing Summit",
    date: "2024-12-10",
    speaker: "Dr. Henry Black",
    completed: false,
  },
  {
    name: "AR/VR Experience Workshop",
    date: "2024-10-20",
    speaker: "Lucas White",
    completed: true,
  },
  {
    name: "Women in Tech Symposium",
    date: "2024-11-25",
    speaker: "Lisa Wong",
    completed: false,
  },
  {
    name: "GreenTech Innovations Expo",
    date: "2024-10-05",
    speaker: "Prof. Daniel Grey",
    completed: true,
  },
  {
    name: "Digital Marketing Summit",
    date: "2024-11-01",
    speaker: "Sarah Jacobs",
    completed: false,
  },
  {
    name: "Future of Work Conference",
    date: "2024-10-02",
    speaker: "Michael Brown",
    completed: true,
  },
  {
    name: "Biotech Revolution Symposium",
    date: "2024-09-27",
    speaker: "Dr. Ivy White",
    completed: false,
  },
  {
    name: "E-Commerce Innovation Forum",
    date: "2024-10-12",
    speaker: "Samantha Grey",
    completed: true,
  },
  {
    name: "Fintech Startup Pitch Day",
    date: "2024-11-10",
    speaker: "Paul King",
    completed: false,
  },
  {
    name: "Women in AI Symposium",
    date: "2024-12-20",
    speaker: "Dr. Natalie Turner",
    completed: false,
  },
  {
    name: "5G & IoT Forum",
    date: "2024-10-30",
    speaker: "Chris Evans",
    completed: true,
  },
  {
    name: "CleanTech World Expo",
    date: "2024-11-15",
    speaker: "Prof. Susan Collins",
    completed: false,
  },
  {
    name: "Innovation in EdTech",
    date: "2024-09-23",
    speaker: "Dr. Mark Green",
    completed: true,
  },
  {
    name: "E-Learning Symposium",
    date: "2024-12-05",
    speaker: "Patricia Hernandez",
    completed: true,
  },
  {
    name: "AI for Social Good Forum",
    date: "2024-11-22",
    speaker: "John Nguyen",
    completed: true,
  },
  {
    name: "HealthTech Innovations",
    date: "2024-10-01",
    speaker: "Dr. Michael Black",
    completed: true,
  },
  {
    name: "Virtual Reality Meetup",
    date: "2024-09-29",
    speaker: "Ellen Adams",
    completed: false,
  },
  {
    name: "Quantum AI Summit",
    date: "2024-11-08",
    speaker: "Robert Cooper",
    completed: true,
  },
  {
    name: "Digital Transformation Summit",
    date: "2024-12-15",
    speaker: "Emily White",
    completed: true,
  },
  {
    name: "AgriTech Forum",
    date: "2024-11-28",
    speaker: "Dr. Alan Liu",
    completed: true,
  },
  {
    name: "IoT and Smart Devices Conference",
    date: "2024-10-07",
    speaker: "Peter Adams",
    completed: true,
  },
  {
    name: "SpaceTech Innovations Summit",
    date: "2024-12-12",
    speaker: "Lisa Johnson",
    completed: false,
  },
  {
    name: "Wearable Technology Forum",
    date: "2024-09-25",
    speaker: "James Brooks",
    completed: true,
  },
  {
    name: "Cryptocurrency and Blockchain Summit",
    date: "2024-12-18",
    speaker: "Susan Nguyen",
    completed: false,
  },
  {
    name: "VR/AR Innovations Expo",
    date: "2024-10-13",
    speaker: "Dr. Alice Moore",
    completed: true,
  },
  {
    name: "Techpreneurs Forum",
    date: "2024-11-03",
    speaker: "David Lee",
    completed: false,
  },
  {
    name: "Sustainable Cities Summit",
    date: "2024-09-22",
    speaker: "Prof. Henry Black",
    completed: true,
  },
  {
    name: "Data Science Bootcamp",
    date: "2024-11-17",
    speaker: "Jessica Clark",
    completed: true,
  },
  {
    name: "Robotics & Automation Symposium",
    date: "2024-09-20",
    speaker: "James Parker",
    completed: true,
  },
  {
    name: "Cyber Defense Forum",
    date: "2024-12-03",
    speaker: "Sophie Grey",
    completed: false,
  },
  {
    name: "Women in STEM Leadership Summit",
    date: "2024-11-30",
    speaker: "Dr. Michelle Brown",
    completed: true,
  },
  {
    name: "AI for Business Conference",
    date: "2024-10-21",
    speaker: "Lucas Martinez",
    completed: false,
  },
  {
    name: "Future of Robotics Forum",
    date: "2024-12-08",
    speaker: "Dr. Richard Black",
    completed: true,
  },
  {
    name: "Green Energy Solutions Summit",
    date: "2024-09-24",
    speaker: "Lisa Brown",
    completed: false,
  },
  {
    name: "Internet of Things Expo",
    date: "2024-11-12",
    speaker: "Chris Allen",
    completed: true,
  },
  {
    name: "Advanced Materials Symposium",
    date: "2024-12-17",
    speaker: "Prof. Julia Smith",
    completed: true,
  },
  {
    name: "Healthcare Tech Startup Pitch",
    date: "2024-10-09",
    speaker: "Dr. Anna Grey",
    completed: false,
  },
  {
    name: "Autonomous Vehicles Forum",
    date: "2024-11-09",
    speaker: "David Brown",
    completed: true,
  },
  {
    name: "Smart Healthcare Forum",
    date: "2024-09-21",
    speaker: "Michael Lee",
    completed: true,
  },
  {
    name: "Tech Innovation Festival",
    date: "2024-12-16",
    speaker: "Karen Smith",
    completed: true,
  },
  {
    name: "AI for Healthcare Innovation",
    date: "2024-11-14",
    speaker: "Samantha Green",
    completed: true,
  },
  {
    name: "Data Science Leadership Forum",
    date: "2024-10-03",
    speaker: "Robert King",
    completed: true,
  },
  {
    name: "Cybersecurity in Finance Summit",
    date: "2024-12-14",
    speaker: "Emily Cooper",
    completed: false,
  },
  {
    name: "Innovations in Education",
    date: "2024-11-02",
    speaker: "James White",
    completed: true,
  },
  {
    name: "Cloud Computing Bootcamp",
    date: "2024-12-13",
    speaker: "William Johnson",
    completed: true,
  },
  {
    name: "5G Revolution Conference",
    date: "2024-09-19",
    speaker: "Daniel Adams",
    completed: false,
  },
  {
    name: "CleanTech Startups Pitch",
    date: "2024-10-19",
    speaker: "Linda Moore",
    completed: true,
  },
  {
    name: "EdTech Innovators Meetup",
    date: "2024-11-18",
    speaker: "Jessica Brown",
    completed: true,
  },
  {
    name: "Future of Learning Conference",
    date: "2024-10-22",
    speaker: "Rachel Williams",
    completed: false,
  },
  {
    name: "Space Innovation Summit",
    date: "2024-11-21",
    speaker: "Dr. Ethan Grey",
    completed: true,
  },
  {
    name: "Smart Homes Expo",
    date: "2024-10-28",
    speaker: "Sophie White",
    completed: false,
  },
  {
    name: "Tech Startups Forum",
    date: "2024-09-26",
    speaker: "David Clark",
    completed: true,
  },
  {
    name: "Quantum Computing Revolution",
    date: "2024-12-02",
    speaker: "Lisa Green",
    completed: true,
  },
  {
    name: "AI-Driven Technologies Conference",
    date: "2024-11-04",
    speaker: "Robert Evans",
    completed: false,
  },
  {
    name: "Healthcare Innovations Expo",
    date: "2024-09-18",
    speaker: "Michelle Smith",
    completed: true,
  },
  {
    name: "Digital Leadership Forum",
    date: "2024-11-20",
    speaker: "Karen Clark",
    completeed: true,
  },
  {
    name: "Tech for Social Impact Forum",
    date: "2024-10-14",
    speaker: "Sophie Martinez",
    completed: false,
  },
  {
    name: "Innovative Supply Chain Conference",
    date: "2024-12-11",
    speaker: "Dr. Alex White",
    completed: true,
  },
  {
    name: "AI and Ethics Forum",
    date: "2024-11-06",
    speaker: "Lisa Brown",
    completed: true,
  },
  {
    name: "Tech Leaders Summit",
    date: "2024-10-29",
    speaker: "David Moore",
    completed: false,
  },
  {
    name: "Wearable Devices Forum",
    date: "2024-09-30",
    speaker: "Michael Parker",
    completed: true,
  },
  {
    name: "CleanTech Innovation Meetup",
    date: "2024-12-04",
    speaker: "Jessica Evans",
    completed: true,
  },
  {
    name: "Digital Transformation Bootcamp",
    date: "2024-09-17",
    speaker: "Chris Moore",
    completed: true,
  },
  {
    name: "Smart City Innovation Conference",
    date: "2024-11-26",
    speaker: "James Brown",
    completed: true,
  },
  {
    name: "AI for Education Summit",
    date: "2024-10-16",
    speaker: "Linda Smith",
    completed: false,
  },
  {
    name: "5G for Business Innovation",
    date: "2024-12-19",
    speaker: "Samantha Adams",
    completed: true,
  },
  {
    name: "Blockchain in FinTech Summit",
    date: "2024-09-16",
    speaker: "Robert Green",
    completed: false,
  },
  {
    name: "Tech Women in Leadership",
    date: "2024-11-11",
    speaker: "Emily White",
    completed: true,
  },
  {
    name: "SaaS Revolution Meetup",
    date: "2024-12-06",
    speaker: "Patricia Brown",
    completed: false,
  },
  {
    name: "EdTech Innovations Forum",
    date: "2024-10-08",
    speaker: "Lucas Johnson",
    completed: true,
  },
  {
    name: "Smart Devices for Business",
    date: "2024-11-24",
    speaker: "Daniel Grey",
    completed: true,
  },
  {
    name: "Tech for Climate Change Forum",
    date: "2024-09-15",
    speaker: "Michelle Martinez",
    completed: true,
  },
  {
    name: "Innovation in Education Forum",
    date: "2024-12-07",
    speaker: "John Smith",
    completed: true,
  },
  {
    name: "5G & Connectivity Summit",
    date: "2024-10-17",
    speaker: "Jessica Clark",
    completed: false,
  },
  {
    name: "Blockchain in Healthcare",
    date: "2024-11-07",
    speaker: "Michael White",
    completed: true,
  },
  {
    name: "AI Ethics for Business",
    date: "2024-12-09",
    speaker: "Ethan Brooks",
    completed: false,
  },
  {
    name: "GreenTech and Renewable Energy",
    date: "2024-09-14",
    speaker: "Prof. Susan Lee",
    completed: true,
  },
  {
    name: "IoT Innovations for Business",
    date: "2024-11-29",
    speaker: "Sophie Adams",
    completed: true,
  },
  {
    name: "Tech in Manufacturing Forum",
    date: "2024-09-13",
    speaker: "Robert Clark",
    completed: true,
  },
  {
    name: "Cybersecurity Innovation Conference",
    date: "2024-10-06",
    speaker: "Lucas White",
    completed: true,
  },
  {
    name: "Women in AI and Robotics",
    date: "2024-11-23",
    speaker: "Linda Black",
    completed: false,
  },
  {
    name: "Future of Education Forum",
    date: "2024-12-21",
    speaker: "William Brown",
    completed: true,
  },
  {
    name: "Smart Cities Expo",
    date: "2024-09-12",
    speaker: "David King",
    completed: true,
  },
  {
    name: "AI and Robotics Symposium",
    date: "2024-10-23",
    speaker: "Dr. Jane Lee",
    completed: true,
  },
  {
    name: "Tech Innovation for Nonprofits",
    date: "2024-11-13",
    speaker: "Sophie Brown",
    completed: true,
  },
  {
    name: "SaaS Technology Conference",
    date: "2024-09-11",
    speaker: "Jessica White",
    completed: false,
  },
  {
    name: "Tech in Energy Innovation",
    date: "2024-12-22",
    speaker: "John Clark",
    completed: true,
  },
  {
    name: "Blockchain for Education",
    date: "2024-09-10",
    speaker: "Lucas Adams",
    completed: true,
  },
  {
    name: "AI for Healthcare Bootcamp",
    date: "2024-11-27",
    speaker: "Emily Brown",
    completed: true,
  },
  {
    name: "Future of Tech for Education",
    date: "2024-09-09",
    speaker: "Chris Martinez",
    completed: true,
  },
  {
    name: "5G for Smart Cities Forum",
    date: "2024-10-11",
    speaker: "David Smith",
    completed: false,
  },
  {
    name: "Healthcare AI Bootcamp",
    date: "2024-12-23",
    speaker: "Linda Green",
    completed: true,
  },
  {
    name: "Cybersecurity Innovations Forum",
    date: "2024-09-08",
    speaker: "James Brown",
    completed: true,
  },
  {
    name: "Women in CleanTech Summit",
    date: "2024-10-04",
    speaker: "Jessica King",
    completed: false,
  },
  {
    name: "AI in Healthcare Summit",
    date: "2024-12-24",
    speaker: "Dr. Robert Adams",
    completed: true,
  },
  {
    name: "Tech for Social Change Forum",
    date: "2024-09-07",
    speaker: "Lucas Brown",
    completed: true,
  },
  {
    name: "Green Energy Innovations Expo",
    date: "2024-10-24",
    speaker: "Patricia White",
    completed: true,
  },
  {
    name: "Smart Devices in Healthcare",
    date: "2024-11-16",
    speaker: "Dr. Robert Grey",
    completed: false,
  },
  {
    name: "Sustainable Agriculture Forum",
    date: "2024-09-06",
    speaker: "David Green",
    completed: true,
  },
  {
    name: "Wearables for Healthcare",
    date: "2024-12-25",
    speaker: "Lisa Martinez",
    completed: true,
  },
];
